### ISSUE TITLE
自定义参数

### ISSUE THREAD

**Issue by huangboju** [meili/MGJRouter#16]
<img width="959" alt="2017-03-03 9 34 56" src="https://cloud.githubusercontent.com/assets/14818224/23534715/b87ab7ce-fff4-11e6-9ae1-b5ab4254d2ff.png">
<img width="275" alt="2017-03-03 9 37 48" src="https://cloud.githubusercontent.com/assets/14818224/23534796/2c33a98c-fff5-11e6-8ec3-b76f4852f633.png">

为什么`query=bicycle`,`bicycle`应该是一个URL的path吧

**Comment by lzyy** [comment]
因为 pattern 里指定了 `:query`，如果把 `:query` 换成 `:keyword` 应该会清晰些。
