### ISSUE TITLE
请教使用方式

### ISSUE THREAD

**Issue by GitterYang** [meili/MGJRouter#19]
您好，有2个问题请教下：
1. 是不是应该在application:didFinishLaunchingWithOptions:中注册所有模块的url?
2.如果模块A跳到模块B了，等B返回时，要刷新A的页面，是不是要通过发送通知才可以？

**Comment by lzyy** [comment]
1. 是的。
2. 如果只是 B 返回要刷新页面，其他页面返回不需要，那么 B 发通知，A 来接比较合适；如果从任何页面返回都要刷新，可以考虑在 `viewDidAppear` 里做点文章。

**Comment by GitterYang** [comment]
多谢了，明白了
