### ISSUE TITLE
如何利用MGJRouter做页面跳转？

### ISSUE THREAD

**Issue by erickyim** [meili/MGJRouter#22]
1. 因为`[[UIApplication sharedApplication] openURL:]`可以做应用间的跳转，所以是否可以用`MGJRouter `的`openURL `做应用内的页面跳转？
2. 如何使用`MGJRouter `从模块A的ControlllerA跳转到模块B的ControllerB？

我所想到的跳转方式如下:

在ModuleB.ControlllerB中注册页面
```
+ (void)load {
    [MGJRouter registerURLPattern:@"mgj://controller/controller_B" toObjectHandler:^id(NSDictionary *routerParameters) {
        UIViewController *controller = [[self alloc] init];
        controller.view.backgroundColor = [UIColor whiteColor];
        controller.title = routerParameters[@"title"];
        return controller;
    }];
}
```
在ModuleA.ControlllerA中做跳转逻辑
```
- (void)pushViewController {
    UIViewController *controller = [MGJRouter objectForURL:@"mgj://controller/controller_B?title=controller_A" withUserInfo:nil];
    [self.navigationController pushViewController:controller animated:YES];
}
```

**Comment by erickyim** [comment]
Demo中的几个例子都是在讲`registerURL`和`openURL`，并没有涉及到页面跳转。据我的理解，`registerURL`是注册事件，`openURL`是传递参数；那么跳转的逻辑要在注册的事件中处理，可是如何处理呢？

**Comment by lzyy** [comment]
> 因为 `[[UIApplication sharedApplication] openURL:]` 可以做应用间的跳转，所以是否可以用MGJRouter的openURL做应用内的页面跳转？

可以的，蘑菇街现在就是这么做的。

> 如何使用MGJRouter从模块A的ControlllerA跳转到模块B的ControllerB？

你的方法 OK 的。蘑菇街由于只有一个 NavigationController，所以在需要跳转的地方直接 `[MGJRouter openURL:@"scheme://url"]`。然后在注册 URL 的 callback 里处理所有的生成 VC 和跳转的逻辑。用的是 `+ (void)registerURLPattern:(NSString *)URLPattern toHandler:(MGJRouterHandler)handler;` 这个方法，在 handler 里完成所有逻辑。

**Comment by erickyim** [comment]
好的，明白了，谢谢！
