### ISSUE TITLE
在+ (void)load中注册,每次启动时都要把所有的注册block存储到字典中, 会不会很耗内存?

### ISSUE THREAD

**Issue by shanbozhu** [meili/MGJRouter#27]
在+ (void)load中注册,每次启动时都要把所有的注册block存储到字典中, 会不会很耗内存?

**Comment by 2360219637** [comment]
我觉得不仅耗内存，还影响到启动时间吧

**Comment by lzyy** [comment]
`+ (void)load` 注册不是必选项，可以在 `AppDelegate` 的 `didFinishLaunchingWithOptions:` 里进行统一管理。

至于注册 block 是否耗内存，block 本质上也是一个 `struct`，它并不会占用多少内存，block 里面的代码也只有到了满足 route 匹配条件时才会被触发。因此内存这块不需要担心。
