### ISSUE TITLE
如何高效地实现代码复用？

### ISSUE THREAD

**Issue by RecherJ** [meili/MGJRouter#30]
最近使用MGJRouter发现一个问题，也想请教下作者，比如我的项目是TabbarController 作为根控制器，有4个NavigationController包装的模块，我在A中注册了一个这样的路由

```swift
MGJRouter.registerURLPattern(serviceURL) { (_) -> Any? in
     let msgListVc = MessageCategoryListController()
     self.navigationController?.pushViewController(msgListVc, animated: true)
     return msgListVc
 }
```
如果都在A组件中使用，那么我只需要像这样打开即可
```swift
MGJRouter.openURL(serviceURL)
```
非常方便，nice！
但B组件也需要用到这个 `serviceURL ` 路由，那我在B组件中是这样的
```swift
let serviceVC = MGJRouter.object(forURL: serviceURL) as! UIViewController
self.navigationController?.pushViewController(serviceVC, animated: true)
```
但这里有一个问题，B组件和A组件中的NavigationController不是同一个实例，所以当去找一个已注册的路由时，其实是执行了注册时的那个block的，这样就有问题。
那我尝试用这个方法去注册上面的路由
```objc
+ (void)registerURLPattern:(NSString *)URLPattern toHandler:(MGJRouterHandler)handler;
```
注册将会是这样
```swift
MGJRouter.registerURLPattern(serviceURL) { (_)  in
     let msgListVc = MessageCategoryListController()
     return msgListVc
 }
```
那我就需要在A组件中也使用类似这样的打开方式
```swift
self.navigationController?.pushViewController(serviceVC, animated: true)
```
如果路由很多时似乎就不是很优雅了.. 又比如携带参数的话，代码很可能就会是这样的（可能不对）
```swift
MGJRouter.openURL(orderListURL, withUserInfo: ["stateType": state], completion: nil)
let serviceVC = MGJRouter.object(forURL: orderListURL) as! UIViewController
self.navigationController?.pushViewController(orderListURL, animated: true)
```
这样确实起到了解耦的目的，但似乎和传统的方式在代码量上并没有减少，如果B组件中也要使用A组件的某个路由，上面的代码也需要在写一遍，并且如果业务逻辑改了，那还是满篇要改路由。
请问这个问题该如何解决呢？

我不清楚我使用的姿势是否正确，如果理解不对还请指出~

**Comment by Blankdlh** [comment]
你好，我先来理解一下你的问题。本质上你提到了两个问题：
1. 存在多个 NavigationController
2. 由于存在多个 NavigationController，那么需要通过 Router 来取到 Object 后手动调用 Push，这个场景下不能在 block 中调用 push。

我来分享一下我们是怎么处理这些问题的，希望能对你有些帮助。

首先从我们对 Router 的定位说起。开源版本的 MGJRouter 是比较灵活的，支持通过 URL 执行某个 block，或者根据 URL 获取一个对象。早期我们内部的确也是这么用的，但是随着项目不断扩大，这里的灵活性其实带来了一些副作用，Router 的功能是存在歧义的。因此，我们在后续使用中，对 Router 做了限制，Router 只允许承载页面跳转的场景。而组件间的调用，通过独立的服务化框架去实现，尽量让 Router 的功能更简单。

再回到你的问题，当 Router 只能做跳转的时候，那么问题就变成了怎么确定要使用哪个 NavigationController。以下解决思路仅供参考：

* 全局只存在一个 NavigationController
* 不使用系统的 TabBarController，自己实现 TabbarController，并作为 NavigationController 的 RootViewController

据我了解，业内除了蘑菇街以外，手淘、闲鱼等 App 也是这么处理的，当然有的 App 甚至连 NavigationController 也自己实现了。相比 NavigationController，TabBarController 交互比较简单，自己实现的成本相对较小。

**Comment by RecherJ** [comment]
@Blankdlh 非常感谢！

**Comment by JpacheGitHub** [comment]
有个问题想问一下, 如果全局只有一个nav, 那比如 tabbar 上有 item, 对应的四个 vc 上面的导航栏是用全局的 nav 来展示, 分别有一个 nav, 但只是用来看的, 跳转还是用全局的, 

如果是用全局 nav 来展示, 那如何做 nav 上 barButtonItem 的变换, 在 - viewWillAppear: 里面做么. 这样不是每次 viewWillAppear: 都要重新创建一个...

如果做一个只是用来看的 nav, 因为要在这四个页面将全局 nav 进行隐藏, push 第一个页面的时候显示出来, 这样全局 nav 就和第二个页面作为一个整体出来了, 而没有了平滑的动效变换.
比如微信, 首页列表跳转聊天详情时, 看上去应该是同一个 nav, 而任何页面跳转到 web 页面时候应该是两个 nav 之间的跳转, 如果像这样, 是不是就应该是只在需要的时候才使用这个全局的 nav, 是不是就不适合在 block 中 push 了.

**Comment by JpacheGitHub** [comment]
@Blankdlh 请教下, 对于全局只有一个Navi, 那么在TabBar上的viewControllers里面放的就应该是UIViewController, 而不是传统方式的放置UINavigationController了, 这样的话, 如何处理TabBar上UIViewController中的navigationItem的问题呢, 在- viewWillAppear:中设置么, 不然会被最后初始化的VC的设置覆盖掉的, 对于这些VC, 设置的时候也不能使用self.title了, 而是要写TabBarController.title? 包括navigationItem里面的东西? 有没有更好的解决方案, 觉得这种方式不好看...
我现在的结构是下面这样的

> UINavigationController
>> UITabBarController
>>> UIViewController
>>> UIViewController
>>> UIViewController
>>> UIViewController

就是在第三层的VC, 对于 navigationItem 的设置

**Comment by yyny1789** [comment]
@JpacheGitHub 
> 可以使用这样结构
> 
> > UINavigationController
> > > UITabBarController
> > > > UINavigationController
> > > > > UIViewController
> > > > UINavigationController
> > > > > UIViewController
> > > > UINavigationController
> > > > > UIViewController
> > > > UINavigationController
> > > > > UIViewController

**Comment by JpacheGitHub** [comment]
> @JpacheGitHub
> 可以使用这样结构
> 
> > UINavigationController
> > > UITabBarController
> > > > UINavigationController -> UIViewController
> > > > UINavigationController -> UIViewController
> > > > UINavigationController -> UIViewController
> > > > UINavigationController -> UIViewController

这样的结构push的时候如果还是要用第三层的nav, 而不是统一用root层nav, 其实就违背了使用全局唯一nav跳转的初衷
如果直接用root层的nav跳转, 那么所有二级页面就要做navBarHidden:animated:的处理, 因为root的navBar是要隐藏的
这里至今没找到好方法, 还是把tabbar的viewContrllers的navItem设置放在了viewWillAppear里...问题倒是不大...
感谢回复^_^

**Comment by yyny1789** [comment]
@JpacheGitHub 
> 这样的结构push的时候如果还是要用第三层的nav, 而不是统一用root层nav, 其实就违背了使用全局唯一nav跳转的初衷
没有必要一定使用全局唯一nav。
