### ISSUE TITLE
路由表呢？

### ISSUE THREAD

**Issue by HaiTeng-Wang** [meili/MGJRouter#33]
“路由通常根据路由表（一个存储到各个目的地的最佳路径表）来引道分组传送；
经过一些中间的节点后，到它们最后的目的地；”

我觉得，路由只需要通过路由表注册一次就好。

所有的路由开源库，包括MGJRouter貌似都忽略了路由表的存在。

你觉得呢？

**Comment by lzyy** [comment]
`MGJRouter` 内部有一个路由信息表，也只需注册一次，您的意思是？

**Comment by HaiTeng-Wang** [comment]
内部的成员成员变量（可变字典），存储所有的路线（url）。所以，可以理解为路由表。我的意思是，为什么不提供个接口，让使用者可以直接传一个字典（路由表）进来。

**Comment by HaiTeng-Wang** [comment]
- (void)registered:(NSDictionary *)routingTable;
- (void)routeHandling:(NSString *)route Handler:(MGJRouterHandler)handler;

大概这个意思。可以通过路由表注册一次就好。根据路线处理不同事件。寻址：直接open, 触发回调。

**Comment by lzyy** [comment]
可以是可以，但我觉得意义不大
